- name: Gather facts
  hosts: postgresql
  become: True
  gather_facts: True

- name: Configure Primary PostgreSQL Host for Streaming Replication
  hosts: postgresql[0]
  become: True
  gather_facts: False
  roles:
    - role: postgresql_primary
      postgresql_secondary_ip: "{{ hostvars[groups['postgresql'][1]]['ansible_default_ipv4']['address'] }}"

- name: Configure Secondary PostgreSQL Host for Streaming Replication
  hosts: postgresql[1]
  become: True
  gather_facts: False
  roles:
    - role: postgresql_secondary
      postgresql_primary_host: "{{ hostvars[groups['postgresql'][0]]['ansible_host'] }}"
